swagger: '2.0'
info:
  title: 45 Client
  description: ->
    This Api defines how the 45 client will receive data from the server
  version: 1.0.0
host: localhost #for testing/development
basePath: /45Client
schemes:
  - http

produces:
  - application/json

consumes:
  - application/json

paths:
  /add-card:
    post:
      summary: Broadcast, notifies clients to add card to their board
      description: >-
        Sends requests to all players saved in the game object, telling players to add this 
        card to their board.

      parameters:
        - name: card
          in: body
          schema:
            $ref: '#/definitions/server-card'

      responses:
        '200':
          description: 'Confirmation of successful request'

        '400':
          description: 'Bad Request, required fields not there or badly formed'

        '404':
          description: 'Service not found'

        '500':
          description: 'Internal server error'


  /end-hand/{playerNo}:
    post:
      summary: Broadcast, which player won the hand
      description: >-
        Sends request to all players, telling them them that the hand is over and who won that hand 
        the players will then clear their board, update thier personal scoreboard and reset the game
        turn, ready for a new hand. The first player of the next trick is the player who won.

      parameters:
        - name: playerNo
          in: path
          type: integer
          required: true

      responses:
        '200':
          description: 'Confirmation of successful request'

        '400':
          description: 'Bad Request, required fields not there or badly formed'

        '404':
          description: 'Service not found'

        '500':
          description: 'Internal server error'

  /end-round/{trump}:
    post:
      summary: Broadcast, gives out a new hand of cards to the players
      description: >-
        Once the players have played all the cards in their hand, the round is over and they will be broadcast a new set of cards.
        They will also be broadcast the suit of the trump card for that round.

      parameters:
        - name: trump
          in: path
          type: string
          required: true

        - name: newHand
          in: body
          schema:
            $ref: '#/definitions/new-hand'

      responses:
        '200':
          description: 'Confirmation of successful request'

        '400':
          description: 'Bad Request, required fields not there or badly formed'

        '404':
          description: 'Service not found'

        '500':
          description: 'Internal server error'

  /end-game/{playerNo}:
    post:
      summary: Broadcast, which player has won the game
      description: >-
        Once one of the players has reached a score of 45, this request signals that the game is over and includes the winning player.

      parameters:
        - name: playerNo
          in: path
          type: integer
          required: true

      responses:
        '200':
          description: 'Confirmation of successful request'

        '400':
          description: 'Bad Request, required fields not there or badly formed'

        '404':
          description: 'Service not found'

        '500':
          description: 'Internal server error'

  /start-game/{trump}/{playerCount}:
    post:
      summary: Broadcast, tells clients to start the game
      description: >-
        Once all the players have joined the game, this request will put the players on the start screen
        and tell them the trump for this round.

      parameters:
        - name: trump
          in: query
          type: string
          required: true

        - name: playerCount
          in: query
          type: integer
          required: true

        - name: newHand
          in: body
          schema:
            $ref: '#/definitions/new-hand'

      responses:
        '200':
          description: 'Confirmation of successful request'

        '400':
          description: 'Bad Request, required fields not there or badly formed'

        '404':
          description: 'Service not found'

        '500':
          description: 'Internal server error'



definitions:
  suit-enum:
    type: string
    example: 'Heart'
    enum:
      - Heart
      - Diamond
      - Spade
      - Club

  server-card:
    type: object
    properties:
      suit:
        description: 'The suit of the card'
        $ref: '#/definitions/suit-enum'
      number:
        description: 'The number of the card, A J Q K Joker is 0,11,12,13,14'
        example: 5
        type: integer

      power:
        description: 'The power of the card, based on its suit and number'
        example: 8
        type: integer

      player:
        description: 'The player id of the player who played the card'
        example: 2
        type: integer

  new-hand:
    type: array
    items:
      $ref: '#/definitions/server-card'





